---
# tasks file for ovirt-engine-install-packages
- name: yum install engine
  yum:
    name: "{{ ovirt_engine_type }}"
    state: installed
    update_cache: yes
  tags:
    - skip_yum_install_ovirt_engine

- name: yum install dwh
  yum:
    name: "{{ ovirt_engine_type }}-dwh"
    state: present
  when: (ovirt_engine_dwh|bool == True) and (ovirt_engine_version|int < 4)
  tags:
    - skip_yum_install_ovirt_engine_dwh

- name: yum install ovirt-engine-dwh-setup
  yum:
    name: "{{ ovirt_engine_type }}-dwh-setup"
    state: present
  when: ovirt_engine_dwh|bool == True
  tags:
    - skip_yum_install_ovirt_engine_dwh_setup

- name: yum install ovirt-engine-extension-aaa-ldap
  yum:
    name: "{{ ovirt_engine_type }}-extension-aaa-ldap"
    state: present
  when: ovirt-engine-extension-aaa-ldap|bool == True
  tags:
    - skip_yum_install_ovirt_engine_extension_aaa_ldap
